name: tuti-cli
recipe: laravel

config:
  php: '8.4'
  webroot: public

excludes:
  - vendor
  - node_modules

services:
  appserver:
    type: php:8.4
    build_as_root:
      - apt-get update -y
      - apt-get install -y nano libsodium-dev sqlite3
    build:
      # Copy .env if not exists
      - '[ ! -f ".env" ] && cp .env.example .env || echo ".env already present"'
    overrides:
      # Mount the project directory
      volumes:
        - ./:/app:cached
        - /var/run/docker.sock:/var/run/docker.sock

tooling:
  npm:
    service: node
    description: Run npm commands
    cmd: npm
